config/routes.rb
Rails.application.routes.draw do

  root to: "blogs#index"
  
  devise_for :users

  # 下記一行だけでentriesに関するindex,new,create,edit,update,destroyアクションが追加される。
  resources :blogs do
    resources :entries, except: [:index] do
      resources :comments, only: [:create, :destroy] do
        put 'approve', on: :member
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord

  #--------------------
  # etc
  #--------------------
  mount_uploader :blog_logo, BlogLogoUploader

  #--------------------
  # relation
  #--------------------
  has_many :entries

  #--------------------
  # validation
  #--------------------
  validates :title, presence: true

  #--------------------
  # enum
  #--------------------
  enumerize :status, in: [:active, :inactive], predicates: { prefix: true }, scope: true

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @q = Blog.ransack(params[:q])
    @blogs = @q.result(distinct: true)
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :status, :blog_logo, :remove_blog_logo)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.haml
= form_for @blog do |f|
  - if @blog.errors.any?
    #error_explanation
      %h2= "#{pluralize(@blog.errors.count, "error")} prohibited this blog from being saved:"
      %ul
        - @blog.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
    = f.label :status
    = f.select :status, Blog.status.options
    = f.label :blog_logo
    = f.file_field :blog_logo
    = image_tag(@blog.blog_logo_url) if @blog.blog_logo?
    = image_tag(@blog.blog_logo_url(:thumb)) if @blog.blog_logo?
    = "削除"
    = f.check_box(:remove_blog_logo)

  .actions
    = f.submit 'Save'

app/views/blogs/edit.html.haml
%h1 Editing blog

= render 'form'

= link_to 'Show', @blog
\|
= link_to 'Back', blogs_path

app/views/blogs/index.html.haml
%h1 Listing blogs

= search_form_for @q do |f|
  =# sort_link(@q, :title)
  =# sort_link(@q, :status)
  = sort_link(@q, :title, %i(title status), "Title + Status", default_order: { status: 'asc', title: 'asc' })
  = f.label :status_eq
  = f.select :status_eq, Blog.status.values, include_blank: true
  = f.label :name_cont
  = f.search_field :title_cont
  = f.submit

%hr

%table
  %thead
    %tr
      %th Status
      %th Title
      %th Blog Logo
      %th
      %th
      %th

  %tbody
    - @blogs.each do |blog|
      %tr
        %td= blog.status_text
        %td= blog.title
        %td= image_tag(blog.blog_logo_url(:thumb)) if blog.blog_logo?
        %td= link_to 'Show', blog
        %td= link_to 'Edit', edit_blog_path(blog)
        %td= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Blog', new_blog_path

app/views/blogs/new.html.haml
%h1 New blog

= render 'form'

= link_to 'Back', blogs_path

app/views/blogs/show.html.haml
%p#notice= notice

%p
  %b Status:
  = @blog.status_text
%p
  %b Title:
  = @blog.title
%p
  %b Blog Logo:
  = image_tag(@blog.blog_logo_url) if @blog.blog_logo?
  = image_tag(@blog.blog_logo_url(:thumb)) if @blog.blog_logo?

= link_to 'Edit', edit_blog_path(@blog)
\|
= link_to 'Back', blogs_path


-#------------------------------
-# 以下、関連するEntryの一覧
-#------------------------------


%h1 Entries

%table
  %thead
    %tr
      %th Title
      %th Body
      %th{colspan: "3"}
  %tbody
  - @blog.entries.each do |entry|
    %tr
      %td= entry.title
      %td= entry.body
      %td= link_to 'Show', [@blog, entry]
      %td= link_to 'Edit', edit_blog_entry_path(@blog, entry)
      %td= link_to 'Destroy', [@blog, entry], method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Entry', new_blog_entry_path(@blog)