config/routes.rb
Rails.application.routes.draw do

  root to: "blogs#index"
  
  devise_for :users

  # 下記一行だけでentriesに関するindex,new,create,edit,update,destroyアクションが追加される。
  resources :blogs do
    resources :entries, except: [:index] do
      resources :comments, only: [:create, :destroy] do
        put 'approve', on: :member
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/entry.rb
class Entry < ApplicationRecord
  # Entryに関する業務ロジックはここに追加する。
  # その他、データベース上の他のテーブルとの関係性などもここに追加する。

  #--------------------
  # relation
  #--------------------
  belongs_to :blog
  has_many :comments

  #--------------------
  # validation
  #--------------------

  #--------------------
  # enum
  #--------------------

  #--------------------
  # scope
  #--------------------
  scope :partial_match_with_title, -> (title) { where("entries.title like ?", "%#{title}%") }

end

app/controllers/entries_controller.rb
# Entriesテーブルの操作を全て受け持つコントローラ
class EntriesController < ApplicationController
  # レコードが指定されたアクションの場合は、まずそのレコードをロードする必要があるので、共通処理としてアクションの前にレコードのロード処理を行う。
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries/1
  # GET /entries/1.json
  def show
    # 指定されたレコードを表示するが、レコードのロードはbefore_actionで指定したset_entryで行なっているため、その他に必要な処理がない。
    # もちろん、必要がある処理は追加する。
    @comment = Comment.new
  end

  # GET /entries/new
  def new
    # 新規レコードであるため空のオブジェクトを作成しておく。
    @entry = Entry.new
    @entry.blog_id = params[:blog_id]
  end

  # GET /entries/1/edit
  def edit
    # showと同じ意味で、処理が書かれていない。
  end

  # POST /entries
  # POST /entries.json
  def create
    # 送信されたデータをEntryオブジェクトに設定している
    @entry = Entry.new(entry_params)
    @entry.blog_id = params[:blog_id]

    # 要求されているレスポンスデータのフォーマットの違いにより処理が分かれている。この場合は、htmlからjsonで処理が分かれている。
    respond_to do |format|
      # 保存処理。trueであればバリデーション成功。falseであればバリデーション失敗。
      if @entry.save
        # htmlの場合。成功した場合は、showの画面にリダイレクト。更新処理後はリダイレクトすることが好ましい。noticeで登録後のメッセージを追加している。
        format.html { redirect_to [@entry.blog, @entry], notice: 'Entry was successfully created.' }
        # jsonの場合。HTTPステータスコードは201となっている。locationは、jsonの中に指定するこのリソースのURL。
        format.json { render :show, status: :created, location: [@entry.blog, @entry] }
      else
        # バリデーションに失敗した場合は、フォームの画面を再表示する。
        format.html { render :new }
        # json形式でエラーの内容を返す。
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      # データベースからロードしたオブジェクトを、送信されたデータで上書きし、DB保存処理を行う。
      if @entry.update(entry_params)
        format.html { redirect_to [@entry.blog, @entry], notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: [@entry.blog, @entry] }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    # DBから削除する。
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to @entry.blog, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # 「/entries/1」というようなURLで、どのレコードが対象であるか特定されている場合は、前処理としてそのレコードをロードする。共通処理なのでメソッド化されている。
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.eager_load(:blog).where(entries: {blog_id: params[:blog_id]}).find(params[:id])
    end

    # 送信されたデータは「entries: {xxx: xxx, yyy: yyy}」という形式になっているが、まずentriesが存在していることをチェックし、なければエラーが発生する。
    # またpermitで指定されたもののみ許可され、それ以外のデータは無視され、ログにwarningが出力される。
    # セキュリティの問題。
    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:title, :body)
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<%# このファイルは、new, editで共有されている。新規登録時も修正時も内容が同じ場合が多いから。もちろん、異なる場合は別々にして良い。 %>
<%# form_withはrails5.1からの機能。entryオブジェクトを元にURLが自動生成されている。local: trueはAjaxを使用しない指定。%>
<%= form_with(model: entry, local: true) do |form| %>
  <%# 保存時にエラーがあった場合%>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <%# エラー件数を表示 %>
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <%# エラーの内容を全て表示 %>
      <%# このレコードに関するエラーはerrorsで参照できる。 %>
      <ul>
      <% entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%# 入力フィールドやチェックボックスなど、それらを表示。 %>
  <div class="field">
    <%# i18n機能を使えば、そこで設定された名前で表示される。 %>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <%# ボタン %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/entries/_form.html.haml
= simple_form_for(entry, url: url_for([entry.blog, entry])) do |form|
  - if entry.errors.any?
    %div#error_explanation
    %h2= pluralize(entry.errors.count, "error") + "prohibited this entry from being saved:"

    %ul
      - entry.errors.full_messages.each do |message|
        %li= message
  %div.field
    = form.input :title, as: :with_length, input_html: {size: 20}

  %div.field
    = form.input :body

  %div.actions
    = form.button :submit

app/views/entries/edit.html.erb
<h1>Editing Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/edit.html.haml
%h1= "Editing Entry: #{@entry.blog.title}"

= render 'form', entry: @entry

= link_to 'Show', [@entry.blog, @entry]
|
= link_to 'Back', @entry.blog

app/views/entries/index.html.erb
<%# frash機能を使ってメッセージが保存されていた場合は、ここで表示する %>
<p id="notice"><%= notice %></p>

<h1>Entries</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.title %></td>
        <td><%= entry.body %></td>
        <%# routes.rbにresourceメソッドを使用して設定した場合、各URLを生成するメソッドが自動生成される。edit_entry_pathなど。 %>
        <td><%= link_to 'Show', entry %></td>
        <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
        <%# リンクを押した時にconfirm:の内容が確認ダイアログとして表示される。
        <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entry', new_entry_path %>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Back', entries_path %>

app/views/entries/new.html.haml
%h1= "New Entry: #{@entry.blog.title}"

= render 'form', entry: @entry

= link_to 'Back', @entry.blog

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @entry.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @entry.body %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

app/views/entries/show.html.haml
%h1= @entry.blog.title

%p#notice= notice

%p
  %strong Title:
  = @entry.title

%p
  %strong Body:
  = @entry.body

= link_to 'Edit', edit_blog_entry_path(@entry.blog, @entry)
|
= link_to 'Back', @entry.blog


-#------------------------------
-# 以下、関連するCommentの一覧
-#------------------------------


%h1 Listing comments

%table
  %thead
    %tr
      %th Body
      %th
      %th

  %tbody
    - @entry.comments.each do |comment|
      %tr
        %td= (comment.status == 'approved')? comment.body : '（承認待ち）'
        %td= (comment.status == 'approved')? '' : link_to('Approve', approve_blog_entry_comment_path(@entry.blog, @entry, comment), method: :put)
        %td= link_to 'Destroy', [@entry.blog, @entry, comment], method: :delete, data: { confirm: 'Are you sure?' }

%br

%h1 New Comment

= form_with(model: @comment, local: true, url: url_for([@entry.blog, @entry, @comment])) do |form|
  - if @comment.errors.any?
    %div#error_explanation
    %h2= pluralize(@comment.errors.count, "error") + "prohibited this comment from being saved:"

    %ul
      - @comment.errors.full_messages.each do |message|
        %li= message
  %div.field
    = form.label :body
    = form.text_area :body

  %div.actions
    = form.submit